### ISSUE TITLE
Need to transfer to tc39

### ISSUE THREAD

**Issue by mikesamuel** [mikesamuel/tc39-module-keys#2]
@ljharb This is in [tc39-transfer](https://github.com/tc39-transfer).  It should probably end up in tc39 soon.  Ideally, I'd also get commit rights at some point.

**Comment by ljharb** [comment]
cc @leobalter @littledan @bterlson

**Comment by ljharb** [comment]
You should already have commit rights.

**Comment by leobalter** [comment]
@mikesamuel I sent you an invite to the delegates team at the @tc39 org. I'm now transferring this project.

**Comment by mikesamuel** [comment]
@leobalter Thanks much.  Looks good now.  Closing.

**Comment by leobalter** [comment]
Anytime!
